### ISSUE TITLE
Python3 dependence

### ISSUE THREAD

**Issue by torrewk** [torrewk/Python-Jax-Fast-Stokesian-Dynamics#19]
Minimum Python3 required should be at least 3.10. Otherwise can't read .toml configuration files.

**Comment by dimos99** [comment]
With python 3.11 you get this error while running the tests: AttributeError: module 'scipy.linalg' has no attribute 'tril'.

Apparently, tril needs an older version of scipy that is not compatible with python 3.11.

**Comment by qubixes** [comment]
@dimos99 The dependencies of `jfsd` require scipy==1.10.1, so I don't think it has anything to do with Python. Perhaps you have accidentally upgraded your version of scipy?

In general it would be nice if we could depend on more modern version of libraries and not pin them, but for that we will need to test it out, and @torrewk probably knows best why these versions were chosen.

**Comment by dimos99** [comment]
You're right, I installed freud which upgraded my scipy. I downgraded it again and it works.
