### ISSUE TITLE
Unit tests with pytest

### ISSUE THREAD

**Issue by qubixes** [torrewk/Python-Jax-Fast-Stokesian-Dynamics#4]
Depends on #3 

Start with adding some unit tests. I'm sure given the size of the project this will be an ongoing issue for a while.

**Comment by torrewk** [comment]
Just added 2 (physical) unit tests contained in test_class.py

**Comment by torrewk** [comment]
Added a third test, for Brownian motion.

**Comment by torrewk** [comment]
Added more thermal tests.

**Comment by torrewk** [comment]
#22 Added three more tests, for a total of seven.
